#ifndef TELECOM_TOOLS_ID_MANAGER_H
#define TELECOM_TOOLS_ID_MANAGER_H

#define GUI_MSG_CHECK "GUI_MSG_CHECK"
#define GUI_MSG "GUI_MSG"
#define MOTOR_FEEDBACK_MSG "MOTOR_FEEDBACK_MSG"
#define MOTOR_COMMAND_CHECK "MOTOR_COMMAND_CHECK"
#define MOTOR_COMMAND_MSG "MOTOR_COMMAND_MSG"
#define POSE_FEEDBACK_MSG "POSE_FEEDBACK_MSG"
#define ACTUATOR_FEEDBACK_MSG "ACTUATOR_FEEDBACK_MSG"


#endif  // TELECOM_TOOLS_ID_MANAGER_H